name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    check:
        runs-on: ubuntu-22.04

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
              with:
                  fetch-depth: 1
                  repository: 'vizzuhq/vizzu-lib'
                  ref: 'main'

            - name: Cache node modules
              id: node_modules_ubuntu22
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: node_modules_ubuntu22_${{ hashFiles('package-lock.json') }}

            - name: Set up node modules
              if: steps.node_modules_ubuntu22.outputs.cache-hit != 'true'
              run: |
                  npm install

            - name: Checkout repo
              uses: actions/checkout@v3
              with:
                  fetch-depth: 1
                  repository: 'vizzuhq/vizzu-lib-doc'
                  ref: 'main'
                  path: 'vizzu-lib-doc'

            - name: Format
              run: |
                  npm run format-showcases

            - name: Lint
              run: |
                    npm run lint-showcases
