name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  init:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          repository: 'vizzuhq/vizzu-lib'
          ref: 'main'

      - name: Cache dev-js environment
        id: cache_dev_js_ubuntu22
        uses: actions/cache@v3
        with:
          path: node_modules
          key: cache_dev_js_ubuntu22_${{ hashFiles('package-lock.json') }}

      - name: Init dev-js environment
        if: steps.cache_dev_js_ubuntu22.outputs.cache-hit != 'true'
        run: |
          npm install

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          repository: 'vizzuhq/vizzu-lib-doc'
          ref: 'main'
          path: 'vizzu-lib-doc'

      - name: Format
        run: |
          npx prettier --config .prettierrc -c vizzu-lib-doc/docs vizzu-lib-doc/.github

      - name: Lint
        run: |
          npx eslint --ext .js,.cjs,.mjs --config .eslintrc.cjs vizzu-lib-doc/docs
