name: CI

on:
  workflow_call:

jobs:
  check_ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Cache dev-py environment
        uses: actions/cache@v3
        with:
          path: .venv_vizzu_doc
          key: dev-py-${{ hashFiles('dev-requirements.txt') }}

      - name: Init dev-py environment
        run: |
          make check-dev-py
          make dev-py

      - name: Cache dev-js environment
        uses: actions/cache@v3
        with:
          path: node_modules
          key: dev-js-${{ hashFiles('package-lock.json') }}

      - name: Init dev-js environment
        run: |
          make check-dev-js
          make dev-js

      - name: Check format
        run: make check-format

      - name: Check lint
        run: make check-lint

      - name: Check typing
        run: make check-typing
